### ISSUE TITLE
Separate data publishing on MQTT to a different thread

### ISSUE THREAD

**Issue by SammyOina** [nakujaproject/n2Basestation#1]
https://github.com/nakujaproject/n2Basestation/blob/1e702ac22e627e739891737cbe97bbfdd2c6bbf2/Teststand/modules/dataFetcher.py#L42

this is to prevent blocking on the data fetcher thread

**Comment by rodneyosodo** [comment]
We are using a different implementation. You can check it out here https://github.com/nakujaproject/n2Basestation/commit/302fd110552286a86a33b88bd64ddbeb565daeaa
